### ISSUE TITLE
[DISCUSS] Handling Arrow Versioning

### ISSUE THREAD

**Issue by westonpace** [apache/arrow-cookbook#11]
I think there are a number of questions around Arrow versioning:

1. Should recipes be based on the latest released version of the implementation?  Or should they be based on the nightly build or the latest commit?
2. Should there be recipes that use deprecated methods?  What about methods that have been removed (presumably after having been deprecated for some time)
3. How should we mark features that were only newly added?  Do we just rely on the compatibility matrix or do we specifically call it out in the cookbook (e.g. "Since 5.0.0")?

**Comment by wjones127** [comment]
@westonpace was this discussed elsewhere when you close? I'm particularly interested in "How should we mark features that were only newly added?"

**Comment by westonpace** [comment]
It's been a while but I guess my thinking was that this question was superseded by discussion in #10 .

I think it's good to allow recipes to be developed prior to the feature being released so having some way to mark them would be good.  In general, we probably want some way to mark which versions a particular recipe supports anyways.

At one point in time I had even brainstormed a little how we might support this in the C++ cookbook.  The start recipe macro could take an (optional) minimum version and an (optional) maximum version and then use that information to allow multiple versions of a recipe and make sure to include the min/max on the page when it is being viewed.  However, that thought never made it past brainstorming and each cookbook will have to figure out some way of managing this.
