### ISSUE TITLE
Difference between cookbook and user guide docs

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-cookbook#116]
I'm looking at this repo for the first time and surprised that I see a lot of overlap with the user guide. For example, how to read a CSV file in Python. My prior expectation was that recipes were common but non-trivial uses of Arrow (for example, creating a sub-sample of an Arrow table), rather than simple examples of functionality like shown in the user guide.

How do we define what a recipe is here? And what's the relationship between the user guide and the cookbook?

**Comment by amol-** [comment]
Hi Will,

The Cookbook aims at being a collection of solutions to specific problems that the user can copy/paste in its own code. The cookbook is meant to be an answer to a specific question that the user would probably search on google on stackoverflow.
Some of those questions will be trivial like how to read CSV, some of those will be more advanced, that doesn't matter too much. If there is someone searching for that question the cookbook should have an answer for it.

The standard documentation instead is more focused on learning. It should provide you tutorials (learn by doing) and explanations and examples. Some of those examples might obviously match with cookbook recipes in some trivial cases, but while the code is similar the purpose they serve is very different.

While Arrow doesn't strictly follow the model, https://diataxis.fr/ has a good description of the difference between "How-to Guides" (the cookbook) and "Tutorials" and "Explanation" (the standard arrow docs).

**Comment by wjones127** [comment]
Thanks for the explanation! I think the task-oriented code snippet idea makes a lot of sense. 

If you'd like, I can make a PR to add what you've written here to the CONTRIBUTING.md file?

**Comment by amol-** [comment]
Would be a great addition, my only suggestion would be to add it to README.rst as that's where the introduction to the cookbook and its purpose is currently written: https://github.com/apache/arrow-cookbook#apache-arrow-cookbooks

Also is the landing page for anyone looking at the cookbook for the first time.
