### ISSUE TITLE
Should recipes use / demonstrate deprecated methods?

### ISSUE THREAD

**Issue by westonpace** [apache/arrow-cookbook#12]
Related: Should we leave recipes around that are no longer valid at all on the latest release of Arrow (e.g. the feature has been since removed, presumably after being deprecated for some amount of time)

**Comment by thisisnic** [comment]
My initial thoughts are that we should remove them otherwise it could send out a confusing message to readers.  I suppose as well, this is intrinsically linked to the question of whether we should have multiple versions of the cookbook?

**Comment by westonpace** [comment]
Yes, on later reflection I think this is covered by #10
