### ISSUE TITLE
Read encrypted parquet file from R

### ISSUE THREAD

**Issue by jaimesalvador** [apache/arrow-cookbook#129]
How to pass encryption key in order to read en encrypted parquet file?

**Comment by thisisnic** [comment]
Hi @jaimesalvador , thanks for opening this issue!  Is this something you'd like to see a recipe for, or are you interested in contributing one yourself?

**Comment by jorisvandenbossche** [comment]
Also note that this might not yet be supported? At least for Python, there is still work under way to expose this functionality more easily in Python, see https://github.com/apache/arrow/pull/10450 (and that PR is also adding documentation about this, eg see https://github.com/apache/arrow/blob/f489321b6d86993851a4f3aa9fb6bfcbd3844db2/docs/source/python/parquet.rst#parquet-modular-encryption-columnar-encryption)

**Comment by thisisnic** [comment]
Ah, if this is a feature that is not yet supported, would you mind opening a ticket on [the project's JIRA](https://issues.apache.org/jira/projects/ARROW/issues) with your feature request,  @jaimesalvador?

**Comment by jaimesalvador** [comment]
Hi @thisisnic, 
I have some programs written in C++ that use ARROW/PARQUET in encrypted format, but int order to check the data stored in parquet files, I need a quit way to check it, so I thought R could be useful for me, but I can't find the way to pass the "key" to decrypt the data (in R).

I think there is a feature not supported yet!

I will open a ticket on JIRA

Thanks for your replies.

**Comment by pdabag** [comment]
anyone knows if there was progress in the last 4 years on this?

**Comment by thisisnic** [comment]
The ticket was closed, as this is a question on the cookbook repo asking how to do something that the Arrow R package didn't support, so it was "completed".  

If your comment is a feature request regarding reading encrypted Parquet files in R, you're best off opening an issue on the Arrow repo: https://github.com/apache/arrow

**Comment by pdabag** [comment]
ahh, sorry, i was it seems in mind already in the holiday season. completely missed that i am on the wrong repo searching for stuff. 
thank you for pointing it out. 
happy holidays🎄✨🎉

**Comment by pdabag** [comment]
https://github.com/apache/arrow/issues/30936 (for completeness reasons and also because the internet is a thing humans link things together)
