### ISSUE TITLE
Change builds to use prebuilt binaries

### ISSUE THREAD

**Issue by westonpace** [apache/arrow-cookbook#13]
Right now the CI build is pretty slow and a fair amount of time is spent downloading / installing build dependencies and building Arrow.  We should be able to use prebuilt binaries for this.

This is somewhat related to #10 .  Do we grab the last nightly build or the last released build?

**Comment by thisisnic** [comment]
I think for now we can just get the R bits to grab the last released, and then modify this later once #10 is resolved.
