### ISSUE TITLE
question/request only: any plans to add Rust to this cookbook?

### ISSUE THREAD

**Issue by yuribudilov** [apache/arrow-cookbook#182]
Greetings
I am just wondering if idiomatic Rust will likely to join this list of languages in near future?

If not, what is best language in the cookbook to use as a baseline to "convert" to Rust flavor? C++ ?

thank you

**Comment by alamb** [comment]
I don't know of any -- but it would be awesome to have one. 

Perhaps we could add it to the main arrow-rs docs via https://github.com/apache/arrow-rs/blob/master/arrow/README.md or similar. 

One idea that might be helpful is make the examples more accessable (now you need to know they exist and go digging in the repo for them): https://github.com/apache/arrow-rs/tree/master/arrow/examples

**Comment by westonpace** [comment]
Would we want to add a little blurb to the main page of the cookbook?  Something like:

`Examples of using the Rust implementation can be found in https://github.com/apache/arrow-rs/tree/master/arrow/examples`

This way future readers would know where to look?

**Comment by alamb** [comment]
Proposed PR: https://github.com/apache/arrow-cookbook/pull/185
