### ISSUE TITLE
[Java] Clarify build requirements

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow-cookbook#190]
The [Java CONTRIBUTING.rst page](https://github.com/apache/arrow-cookbook/blob/main/java/CONTRIBUTING.rst) makes no mention of a Python dependency, but the `make java` command can fail due to python-related activity:

```
todd@pop-os:~/arrow-cookbook$ make java
>>> Installing Java Dependencies <<<

cd java && pip install -r requirements.txt
/bin/sh: 1: pip: not found
make: *** [Makefile:27: javadeps] Error 127
```
The [base README.rst file](https://github.com/apache/arrow-cookbook/blob/main/README.rst) references Python in a context that seems specific to R and Python cookbooks.

Python dependencies should be documented.

**Comment by toddfarmer** [comment]
After installing pip, the build script successfully installed required dependencies, but failed due to missing sphinx-build:
```
todd@pop-os:~/arrow-cookbook$ make java
>>> Installing Java Dependencies <<<

cd java && pip install -r requirements.txt
...
>>> Building Java Cookbook <<<

cd java && make html
make[1]: Entering directory '/home/todd/arrow-cookbook/java'
/bin/sh: 1: sphinx-build: not found
make[1]: *** [Makefile:20: html] Error 127
make[1]: Leaving directory '/home/todd/arrow-cookbook/java'
make: *** [Makefile:81: java] Error 2
todd@pop-os:~/arrow-cookbook$ sphinx-build
Command 'sphinx-build' not found, but can be installed with:
sudo apt install python3-sphinx
```

**Comment by westonpace** [comment]
That looks accurate to me, the Java build documents should probably be updated.  Though that is a Java cookbook decision and not a general decision (which is probably why the base readme doesn't specify it).

The c++ cookbook, for example, does not rely on pip, and instead makes use of conda.  One could also make a cookbook that doesn't use sphinx if they chose to.  The R cookbook can be built without sphinx I think.

**Comment by toddfarmer** [comment]
Thanks @westonpace - I'll constrain my proposed changes to the Java CONTRIBUTING file, then.
