### ISSUE TITLE
[R] Broken links in section 2

### ISSUE THREAD

**Issue by andreranza** [apache/arrow-cookbook#276]
It seems all the links in Section 2 are broken.

Below are some examples:

- https://arrow.apache.org/cookbook/r/reading-and-writing-data.html
- https://arrow.apache.org/cookbook/r/reading-and-writing-data.html#write-a-parquet-file
- https://arrow.apache.org/cookbook/r/reading-and-writing-data.html#read-a-feather-file

![Screenshot 2022-11-08 at 15 55 16](https://user-images.githubusercontent.com/43607279/200597663-3cb07444-0f46-4771-a4cd-1970ed83020e.png)

**Comment by thisisnic** [comment]
Hi @andreranza , thanks for reporting this!  Would you mind just clarifying where these links are from?

**Comment by andreranza** [comment]
Sure, these links are from the summary in the cookbook.

So, if I click on those titles, I cannot read the content.

<img width="1904" alt="Screenshot 2022-11-08 at 18 50 46" src="https://user-images.githubusercontent.com/43607279/200639038-eb859509-2361-446b-ad22-fa2542444e80.png">

Thanks for this helpful resource.

**Comment by thisisnic** [comment]
Oh, interesting, it works for me, but we've had issues in the past on other bits of the site with caching on Macs.  Does it work if you press Shift+Command+R to reload without the cache?

**Comment by andreranza** [comment]
Yes, it works. Thanks a lot! I thought these might have broken somehow since I could open other pages by clicking on different sections - titles.

**Comment by thisisnic** [comment]
It's because we updated those sections specifically, so makes sense it looked like something had gone wrong in a different way!
