### ISSUE TITLE
[Release] Update cookbook versions for 16.0.0 release

### ISSUE THREAD

**Issue by amoeba** [apache/arrow-cookbook#348]
We can normally get away with just bumping versions in a minor PR but two issues have already come up in early testing for the 16.0.0 release so I thought I'd track those and anything else we find here ahead of the release.

- [x] Refactor Java cookbooks from jshell to maven to support post-JPMS Arrow
  - [x] https://github.com/apache/arrow-cookbook/issues/347
- [x] Update R cookbook since we now support casting to/from float16()
  - https://github.com/apache/arrow/pull/40067 added support for casting, we need to update that cookbook
  - https://github.com/apache/arrow-cookbook/actions/runs/8656358859/job/23736767598 shows the CI failure and I was able to confirm it locally

**Comment by raulcd** [comment]
Let me know if I can help with anything here @amoeba

**Comment by amoeba** [comment]
Hey @raulcd, this slipped. I'll work on a PR for the Java refactor this week.

**Comment by amoeba** [comment]
I put a PR up at https://github.com/apache/arrow-cookbook/pull/350. I ran into one snag which may require rewriting all Java examples to have an explicit main class. I'd appreciate a review if you have a minute.
