### ISSUE TITLE
gh-pages or Apache hosting?

### ISSUE THREAD

**Issue by westonpace** [apache/arrow-cookbook#9]
It appears that in addition to gh-pages we can use Apache hosting.  The only real difference would be the URLs.

https://apache.github.io/arrow-cookbook
https://arrow.apache.org/cookbook

However, the latter approach may require some synchronization with the main Arrow repository (I'm not sure 100% sure if it is sufficient to just make sure the main arrow site doesn't have a `cookbook` directory).  We might need to ask Infra but I'd rather test if there is interest before doing that.

**Comment by thisisnic** [comment]
That second URL certainly looks nicer, what kind of synchronization might be needed?

**Comment by westonpace** [comment]
Well, the docs for `.asf.yaml` (https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Specifyingasub-directorytopublishto) say you can use a subdirectory but it's not clear to me if that means that all repositories hosting on the same project need to use subdirectories or if one repository is allowed to be the "root" repository and the others are subdirectories inside of that.

**Comment by westonpace** [comment]
![image](https://user-images.githubusercontent.com/1696093/128431859-fe3ceae2-ddc0-43e2-b7c4-67a24b977a87.png)

**Comment by westonpace** [comment]
It should be pretty quick (I hope) to fix whatever we break.  I guess I don't know what the refresh rate is for the site publishing.  I'll ask on Zulip.

**Comment by westonpace** [comment]
I got some more feedback that it should work as long as "there is no overlap and the top project is registered first".  So I think we are good.  Once the gh-pages build is stable I'll give it a shot and hopefully not break the main page :crossed_fingers: I think it might be nice to leave the gh-pages integration in anyways until we get some kind of PR-level staging as it works on forks so people can test their own changes that way.

**Comment by westonpace** [comment]
Either way I think we should leave the current gh-pages integration in.  It's probably not a big deal if it is hosted at two places.  Plus, with the gh-pages I can push to my fork's main and then have my own hosted instance for testing.

**Comment by thisisnic** [comment]
> I got some more feedback that it should work as long as "there is no overlap and the top project is registered first". So I think we are good. Once the gh-pages build is stable I'll give it a shot and hopefully not break the main page crossed_fingers I think it might be nice to leave the gh-pages integration in anyways until we get some kind of PR-level staging as it works on forks so people can test their own changes that way.

> Either way I think we should leave the current gh-pages integration in. It's probably not a big deal if it is hosted at two places. Plus, with the gh-pages I can push to my fork's main and then have my own hosted instance for testing.

All of the above sounds good to me.

**Comment by jorisvandenbossche** [comment]
The gh-pages branch is present, but it seems the url https://apache.github.io/arrow-cookbook is not yet working?

**Comment by westonpace** [comment]
I'm pretty sure the `.asf.yaml` integration is not working for gh-pages.  I've enabled gh-pages on my fork and everything is working correctly.  However, I don't intend to bug ASF too much about it since it seems we are leaning towards Apache hosting anyways.  Although I don't know any good way to test "gh-pages continues to work on local forks".

**Comment by thisisnic** [comment]
I've tried to fix it in #28 after looking at other Apache repositories

**Comment by westonpace** [comment]
I'm going to raise Apache hosting on the ML.  If there is no concern I'll try subdir publishing which should put us at https://arrow.apache.com/cookbook
